name: CI-CD

on: # trigger/event
  push:
    branches: # branches q disparam essa pipe
      - "main"

jobs: # fluxos disparados pela pipe
  CI:
    runs-on: ubuntu-latest # onde ele executa
    steps: # passos de execução desse job
      - name: Checkout #action
        uses: actions/checkout@v3.1.0

      - name: Docker Login #action
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build And Push Docker Image #action
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            hugovallada/live-kube-news:v${{github.run_number}}.0
            hugovallada/live-kube-news:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Kubernetes Set Context # É da Azure, mas serve para todos
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Deploy Kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          images: hugovallada/live-kube-news:v${{github.run_number}}.0
          manifests: |
            k8s/deployment.yaml

